//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_BOOKKEEPING_CONFIGURATION
    {
        public WF_BK_BOOKKEEPING_CONFIGURATION()
        {
            this.WF_BK_CONFIGURATION_CUSTOM_FIELD_MULTIPLE = new HashSet<WF_BK_CONFIGURATION_CUSTOM_FIELD_MULTIPLE>();
            this.WF_BK_CONFIGURATION_CUSTOM_FIELD = new HashSet<WF_BK_CONFIGURATION_CUSTOM_FIELD>();
            this.WF_BK_CONFIGURATION_PAYROLL_YEAR_START_DATE = new HashSet<WF_BK_CONFIGURATION_PAYROLL_YEAR_START_DATE>();
            this.WF_BK_OPERATION_HOURS = new HashSet<WF_BK_OPERATION_HOURS>();
        }
    
        public int BKC_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public string COMPANY_LEGAL_NAME { get; set; }
        public string DBA_NAME { get; set; }
        public decimal OT_MULTIPLIRE { get; set; }
        public Nullable<int> PAYROLL_CYCLE_ID { get; set; }
        public System.DateTime PAYROLL_DATE { get; set; }
        public System.DateTime PAYROLL_END_DATE { get; set; }
        public int INDUSTRY_TYPE_ID { get; set; }
        public int COMPANY_ENTITY_TYPE_ID { get; set; }
        public int ACCOUNTING_SOFTWARE_ID { get; set; }
        public Nullable<int> POS_SOFTWARE_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_MS_SOFTWARE WF_BK_MS_SOFTWARE { get; set; }
        public virtual WF_BK_MS_SOFTWARE WF_BK_MS_SOFTWARE1 { get; set; }
        public virtual WF_BK_PAYROLL_CYCLE WF_BK_PAYROLL_CYCLE { get; set; }
        public virtual ICollection<WF_BK_CONFIGURATION_CUSTOM_FIELD_MULTIPLE> WF_BK_CONFIGURATION_CUSTOM_FIELD_MULTIPLE { get; set; }
        public virtual ICollection<WF_BK_CONFIGURATION_CUSTOM_FIELD> WF_BK_CONFIGURATION_CUSTOM_FIELD { get; set; }
        public virtual ICollection<WF_BK_CONFIGURATION_PAYROLL_YEAR_START_DATE> WF_BK_CONFIGURATION_PAYROLL_YEAR_START_DATE { get; set; }
        public virtual ICollection<WF_BK_OPERATION_HOURS> WF_BK_OPERATION_HOURS { get; set; }
    }
}
