//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_EMPLOYEE
    {
        public WF_BK_EMPLOYEE()
        {
            this.WF_BK_EMPLOYEE_DESIGNATION = new HashSet<WF_BK_EMPLOYEE_DESIGNATION>();
            this.WF_BK_EMPLOYEE_ADDRESS = new HashSet<WF_BK_EMPLOYEE_ADDRESS>();
            this.WF_BK_EMPLOYEE_SCHEDULE = new HashSet<WF_BK_EMPLOYEE_SCHEDULE>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MOBILE_NUMBE { get; set; }
        public Nullable<int> PRIMARY_DESIGNATION { get; set; }
        public int USER_ID { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual ICollection<WF_BK_EMPLOYEE_DESIGNATION> WF_BK_EMPLOYEE_DESIGNATION { get; set; }
        public virtual ICollection<WF_BK_EMPLOYEE_ADDRESS> WF_BK_EMPLOYEE_ADDRESS { get; set; }
        public virtual ICollection<WF_BK_EMPLOYEE_SCHEDULE> WF_BK_EMPLOYEE_SCHEDULE { get; set; }
    }
}
