//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_CREDIT_CARD_DETAILS
    {
        public int CREADIT_CARD_DETAILS_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public string BANK_NAME { get; set; }
        public int CARD_TYPE { get; set; }
        public string CARD_NUMBER { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_MS_CREDIT_CARD_TYPE WF_BK_MS_CREDIT_CARD_TYPE { get; set; }
    }
}
