//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_EMPLOYEE_DESIGNATION
    {
        public int EMPLOYEE_DESIGNATION_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public int DESIGNATION_ID { get; set; }
        public byte PAY_TYPE_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public decimal RATE { get; set; }
        public Nullable<int> CYCLE_ID { get; set; }
        public int USER_ID { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_EMPLOYEE WF_BK_EMPLOYEE { get; set; }
        public virtual WF_BK_MS_DESIGNATION WF_BK_MS_DESIGNATION { get; set; }
    }
}
