//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BILLING_DETAIL
    {
        public int BILL_ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public int VENDOR_ID { get; set; }
        public int DOCUMENT_ID { get; set; }
        public string DOCUMENT_PAGE_NO { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public int PAYMENT_TERM_ID { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public decimal AMOUNT { get; set; }
        public string BILL_DESCRIPTION { get; set; }
        public string NOTE_TO_PAYER { get; set; }
        public Nullable<bool> IS_SPLIT_AMOUNT { get; set; }
        public Nullable<byte> APPROVAL_STATUS { get; set; }
        public Nullable<byte> PAYMENT_STATUS { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public Nullable<decimal> PREVIOUS_AMOUNT { get; set; }
        public Nullable<decimal> CREDIT_APPLIED { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
    
        public virtual WORKFLOW_CUSTOM WORKFLOW_CUSTOM { get; set; }
    }
}
