//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_OPERATION_HOURS
    {
        public int OPERATION_HOURS_ID { get; set; }
        public int BKC_ID { get; set; }
        public byte WEEKDAY { get; set; }
        public Nullable<decimal> OPERATION_HOUR_LABLE_ONE { get; set; }
        public Nullable<decimal> OPERATION_HOUR_LABLE_TWO { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_BOOKKEEPING_CONFIGURATION WF_BK_BOOKKEEPING_CONFIGURATION { get; set; }
    }
}
