//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_MS_DESIGNATION
    {
        public WF_BK_MS_DESIGNATION()
        {
            this.WF_BK_EMPLOYEE_DESIGNATION = new HashSet<WF_BK_EMPLOYEE_DESIGNATION>();
        }
    
        public int DESIGNATION_ID { get; set; }
        public string DESIGNATION_NAME { get; set; }
        public int INDUSTRY_ID { get; set; }
        public int USER_ID { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual ICollection<WF_BK_EMPLOYEE_DESIGNATION> WF_BK_EMPLOYEE_DESIGNATION { get; set; }
    }
}
