//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_MS_KPIS
    {
        public WF_BK_MS_KPIS()
        {
            this.WF_BK_KPIS = new HashSet<WF_BK_KPIS>();
        }
    
        public int KPIS_ID { get; set; }
        public string KPIS_NAME { get; set; }
        public int INDUSTRY_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_MS_INDUSTRY WF_BK_MS_INDUSTRY { get; set; }
        public virtual ICollection<WF_BK_KPIS> WF_BK_KPIS { get; set; }
    }
}
