//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_CONFIGURATION_PAYROLL_YEAR_START_DATE
    {
        public int PAYROLL_YEAR_START_DATE_ID { get; set; }
        public int BKC_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public int PAYROLL_CYCLE_ID { get; set; }
        public System.DateTime PAYROLL_START_DATE { get; set; }
        public int YEAR { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_BOOKKEEPING_CONFIGURATION WF_BK_BOOKKEEPING_CONFIGURATION { get; set; }
    }
}
