//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_EMPLOYEE_ADDRESS
    {
        public int EMPLOYEE_ADDRESS_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public Nullable<byte> COUNTRY_ID { get; set; }
        public Nullable<short> STATE_ID { get; set; }
        public string ZIP { get; set; }
        public int USER_ID { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_EMPLOYEE WF_BK_EMPLOYEE { get; set; }
    }
}
