//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_MS_SOFTWARE_TYPE
    {
        public int SOFTWARE_ID { get; set; }
        public byte SOFTWARE_TYPE_ID { get; set; }
        public string SOFTWARE_TYPE_NAME { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_MS_SOFTWARE_TYPE WF_BK_MS_SOFTWARE_TYPE1 { get; set; }
        public virtual WF_BK_MS_SOFTWARE_TYPE WF_BK_MS_SOFTWARE_TYPE2 { get; set; }
    }
}
