//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_CUSTOMER
    {
        public int CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string PHONE_NO { get; set; }
        public int TYPE_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public Nullable<short> STATE_ID { get; set; }
        public string ZIP { get; set; }
        public Nullable<byte> COUNTRY_ID { get; set; }
        public bool VENDOR_1099 { get; set; }
        public string TAX_ID { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_MS_CUSTOMER_TYPE WF_BK_MS_CUSTOMER_TYPE { get; set; }
    }
}
