//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BK_EMPLOYEE_SCHEDULE
    {
        public int SCHEDULE_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public int WEEK_DAY_ID { get; set; }
        public Nullable<System.TimeSpan> IN_TIME { get; set; }
        public Nullable<System.TimeSpan> OUT_TIME { get; set; }
        public bool IS_OFF_DAY { get; set; }
        public int USER_ID { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_BK_EMPLOYEE WF_BK_EMPLOYEE { get; set; }
    }
}
