//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_CUSTOM_WORKFLOW
    {
        public WF_CUSTOM_WORKFLOW()
        {
            this.WF_CUSTOM_WORKFLOW_CUSTOM_FIELD_MULTIPLE = new HashSet<WF_CUSTOM_WORKFLOW_CUSTOM_FIELD_MULTIPLE>();
            this.WF_CUSTOM_WORKFLOW_CUSTOM_FIELD = new HashSet<WF_CUSTOM_WORKFLOW_CUSTOM_FIELD>();
        }
    
        public int CUSTOM_WORKFLOW_ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<byte> APPROVAL_STATUS { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual ICollection<WF_CUSTOM_WORKFLOW_CUSTOM_FIELD_MULTIPLE> WF_CUSTOM_WORKFLOW_CUSTOM_FIELD_MULTIPLE { get; set; }
        public virtual ICollection<WF_CUSTOM_WORKFLOW_CUSTOM_FIELD> WF_CUSTOM_WORKFLOW_CUSTOM_FIELD { get; set; }
    }
}
