//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_COMMON_FIELDS
    {
        public int WORKFLOW_ID { get; set; }
        public string WORKFLOW_DATE_NAME { get; set; }
        public string WORKFLOW_TITLE { get; set; }
    }
}
