//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_DSR_REPORT
    {
        public WF_DSR_REPORT()
        {
            this.WF_DSR_REPORT_CATEGORY = new HashSet<WF_DSR_REPORT_CATEGORY>();
            this.WF_DSR_REPORT_LINE_ITEM = new HashSet<WF_DSR_REPORT_LINE_ITEM>();
        }
    
        public int DSR_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<byte> REVIEWER_STATUS { get; set; }
        public int CLIENT_ID { get; set; }
        public System.DateTime DSR_DATE { get; set; }
        public Nullable<decimal> OPERATING_HOURS { get; set; }
        public short NO_OF_CHECKS { get; set; }
        public int WORKFLOW_DEFINITION_ID { get; set; }
        public decimal TOTAL_SALES { get; set; }
        public decimal AVERAGE_TOTAL { get; set; }
        public Nullable<decimal> AMEX_CC_RECEIPTS { get; set; }
        public Nullable<decimal> AMEX_CC_TIPS { get; set; }
        public Nullable<decimal> AMEX_CC_SALES_TEX { get; set; }
        public Nullable<decimal> M_V_D_CC_RECEIPTS { get; set; }
        public Nullable<decimal> M_V_D_CC_TIPS { get; set; }
        public Nullable<decimal> M_V_D_CC_SALES_TEX { get; set; }
        public Nullable<decimal> TOTAL_CC_RECEIPTS { get; set; }
        public Nullable<decimal> TOTAL_CC_TIPS { get; set; }
        public Nullable<decimal> TOTAL_CC_SALES_TEX { get; set; }
        public decimal NET_CC_SALES { get; set; }
        public decimal CC_TIPS_PERCENTAGE { get; set; }
        public decimal CASE_SALES { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<WF_DSR_REPORT_CATEGORY> WF_DSR_REPORT_CATEGORY { get; set; }
        public virtual ICollection<WF_DSR_REPORT_LINE_ITEM> WF_DSR_REPORT_LINE_ITEM { get; set; }
    }
}
