//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_DOCUMENT_ENTITIES
    {
        public int DOCUMENT_ENTITY_ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public int ENTITY_ID { get; set; }
        public int DOC_ID { get; set; }
        public int NEW_DOC_ID { get; set; }
        public int USER_ID { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public bool DELETED_FLAG { get; set; }
    }
}
