//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_DOCUMENT_WORKFLOW_ESCALATION
    {
        public int WORKFLOW_ESCALATION_ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public Nullable<byte> APPROVAL_EXPIRE_DAYS { get; set; }
        public Nullable<byte> APPROVAL_EXPIRE_HOURS { get; set; }
        public Nullable<byte> APPROVAL_EXPIRE_MINUTES { get; set; }
        public Nullable<bool> IS_REMINDER { get; set; }
        public Nullable<byte> REMINDER_MINUTES { get; set; }
        public Nullable<int> ESCALATION_TYPE_ID { get; set; }
        public Nullable<int> ESCALATION_USER_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual WF_DOCUMENT_WORKFLOW WF_DOCUMENT_WORKFLOW { get; set; }
    }
}
