//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_INVOICE
    {
        public WF_INVOICE()
        {
            this.WF_INVOICE_ITEM = new HashSet<WF_INVOICE_ITEM>();
        }
    
        public int INVOICE_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public string PO_NUMBER { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public int PAYMENT_TERM_ID { get; set; }
        public string SALE_REP { get; set; }
        public string CUSTOME_MESSAGE { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual ICollection<WF_INVOICE_ITEM> WF_INVOICE_ITEM { get; set; }
    }
}
