//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_ITEM
    {
        public WF_ITEM()
        {
            this.WF_INVOICE_ITEM = new HashSet<WF_INVOICE_ITEM>();
        }
    
        public int ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public decimal RATE { get; set; }
        public bool IS_TAXABLE { get; set; }
        public int ACCOUNT_ID { get; set; }
        public int ITEM_TYPE_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    
        public virtual ICollection<WF_INVOICE_ITEM> WF_INVOICE_ITEM { get; set; }
    }
}
