//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_PAYMENT_RECEIVED
    {
        public int PAYMENT_RECEVIED_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int INVOICE_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public int PAYMENT_TYPE_ID { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public Nullable<int> DEPOSIT_TO { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> DOCUMENT_ID { get; set; }
        public string DOCUMENT_PAGE_NO { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    }
}
