//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_PAYROLL_REPORT
    {
        public int PAYROLL_REPORT_ID { get; set; }
        public int WORKFLOW_DEFINITION_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public string TITLE { get; set; }
        public System.DateTime PAYROLL_REPORT_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<byte> APPROVAL_STATUS { get; set; }
        public int YEAR_START_DAY { get; set; }
        public int YEAR_START_MONTH { get; set; }
        public int YEAR_END_DAY { get; set; }
        public int YEAR_END_MONTH { get; set; }
        public System.DateTime PAYROLL_PERIOD_START_DATE { get; set; }
        public System.DateTime PAYROLL_PERIOD_END_DATE { get; set; }
        public bool IS_RECORDED { get; set; }
        public int PAYROLL_CYCLE_ID { get; set; }
        public System.DateTime PAYROLL_END_DATE { get; set; }
        public System.DateTime PAYROLL_DUE_DATE { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    }
}
