//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_PAYROLL_LINE_ITEMS
    {
        public int PAYROLL_LINE_ITEM_ID { get; set; }
        public int PAYROLL_ID { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public Nullable<int> DESIGNATION { get; set; }
        public double REQUESTED_HOURS { get; set; }
        public double OVERTIME_HOURS { get; set; }
        public Nullable<int> TIME_OFF { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
    }
}
