//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_PAID_CREDIT
    {
        public int PAID_CREDIT_ID { get; set; }
        public string VENDOR_CREDIT_REFERENCE { get; set; }
        public Nullable<int> BILL_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public Nullable<int> VENDOR_CREDIT_ID { get; set; }
    }
}
