//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_TIME_LINE
    {
        public int WORKFLOW_TIME_LINE_ID { get; set; }
        public Nullable<int> APPROVAL_STATUS { get; set; }
        public int EVENT_ID { get; set; }
        public int ENTITY_ID { get; set; }
        public int ENTITY_TYPE { get; set; }
        public Nullable<int> OBJECT_ID { get; set; }
        public Nullable<int> PREVIOUS_OBJECT_ID { get; set; }
        public Nullable<int> OBJECT_TYPE_ID { get; set; }
        public string REMARKS { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public Nullable<bool> IS_ROLE { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
    
        public virtual WF_TIME_LINE_EVENT WF_TIME_LINE_EVENT { get; set; }
        public virtual WF_TIME_LINE_OBJECT_TYPE WF_TIME_LINE_OBJECT_TYPE { get; set; }
    }
}
