//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_TOBEPROCESSED_WIDGET
    {
        public int TOBEPROCESSED_ID { get; set; }
        public int FOLDER_ID { get; set; }
        public int DOC_ID { get; set; }
        public string FOLDER_NAME { get; set; }
        public string SYSTEM_FILE_NAME { get; set; }
        public byte STATUS { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public Nullable<int> WORKFLOW_ID { get; set; }
    }
}
