//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WORKFLOW_MESSAGES
    {
        public WF_WORKFLOW_MESSAGES()
        {
            this.WF_WORKFLOW_MESSAGE_COMMENT = new HashSet<WF_WORKFLOW_MESSAGE_COMMENT>();
            this.WF_WORKFLOW_MSGBOARD_RECIPIENTS = new HashSet<WF_WORKFLOW_MSGBOARD_RECIPIENTS>();
        }
    
        public int MESSAGE_ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public int PROCESS_ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public Nullable<bool> APPEND_SIGNATURE { get; set; }
        public string PLAIN_MESSAGE_DESCRIPTION { get; set; }
        public Nullable<int> MESSAGE_TYPE { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
    
        public virtual ICollection<WF_WORKFLOW_MESSAGE_COMMENT> WF_WORKFLOW_MESSAGE_COMMENT { get; set; }
        public virtual ICollection<WF_WORKFLOW_MSGBOARD_RECIPIENTS> WF_WORKFLOW_MSGBOARD_RECIPIENTS { get; set; }
    }
}
