//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL.WorkFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_DEFINITION
    {
        public WORKFLOW_DEFINITION()
        {
            this.WF_DOCUMENT_WORKFLOW_APPROVAL = new HashSet<WF_DOCUMENT_WORKFLOW_APPROVAL>();
            this.WF_PROCESS = new HashSet<WF_PROCESS>();
            this.WORKFLOW_DEFINITION_ESCALATION = new HashSet<WORKFLOW_DEFINITION_ESCALATION>();
            this.WORKFLOW_DEFINITION_STEPS = new HashSet<WORKFLOW_DEFINITION_STEPS>();
        }
    
        public int WORKFLOW_DEFINITION_ID { get; set; }
        public string WORKFLOW_DEFINITION_TITLE { get; set; }
        public Nullable<int> CUSTOME_FIELD_ID { get; set; }
        public Nullable<int> ACL_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> IS_BOOKKEEPING_CLIENT_SPECIFIC { get; set; }
        public Nullable<byte> APPROVAL_CHANGES_TYPE { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_OF_ENTRY { get; set; }
        public int USER_MODIFIED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool DELETED_FLAG { get; set; }
        public Nullable<byte> WORK_FLOW_LEVEL { get; set; }
        public Nullable<bool> ALLOW_MULTIPLE_ENTRIES { get; set; }
        public string SHORT_TITLE { get; set; }
        public Nullable<bool> IS_SHOW_IN_MENU { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
        public string ITEM_TEXT { get; set; }
        public string ON_CLICK_FUNCTION { get; set; }
        public Nullable<int> MODULE_ID { get; set; }
        public bool ACTIVE_FLAG { get; set; }
    
        public virtual ICollection<WF_DOCUMENT_WORKFLOW_APPROVAL> WF_DOCUMENT_WORKFLOW_APPROVAL { get; set; }
        public virtual ICollection<WF_PROCESS> WF_PROCESS { get; set; }
        public virtual ICollection<WORKFLOW_DEFINITION_ESCALATION> WORKFLOW_DEFINITION_ESCALATION { get; set; }
        public virtual ICollection<WORKFLOW_DEFINITION_STEPS> WORKFLOW_DEFINITION_STEPS { get; set; }
    }
}
